site_name: Documentação de Erros e Processos JCG
site_url: https://idea-technology-it.github.io/docs-jc-gontijo/
site_description: Documentação de Erros e Processos JCG
site_author: 'Pedro Lucas Rodrigues'

# Copyright
copyright: Copyright &copy; 2024 - 2024 Idea Technology

# Configuration
theme:
  language: pt-BR
  name: material
  logo: assets/logo/JC-Logo.png
  favicon: assets/logo/favicon.ico
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - navigation.footer
    - content.tooltips
  palette:
    - scheme: slate
      primary: 'black'
      accent: 'orange'


# Navigation
nav:
  - Introdução: home/index.md
  - Morar Bem:
      - Chamados Recorrentes:
          - Atualizar Data de Entrega de Chaves: topicos/morar-bem/chamados/atualizar-data-entrega-chaves.md
          - Atualizar Valor Taxa de Cartório: topicos/morar-bem/chamados/atualizar-valor-taxa-cartorio.md
          - Atualizar Valor Unidade: topicos/morar-bem/chamados/atualizar-valor-unidade.md
          - Criar Usuários: topicos/morar-bem/chamados/criar-usuario.md
          - Gravar Histórico/Nota : topicos/morar-bem/chamados/gravar-historico.md
          - Inclusão de Boletos de Taxa de Cartório: topicos/morar-bem/chamados/inclusao-boletos-tx-cartorio.md
      - Processos:
          - Deploy: topicos/morar-bem/processos/deploy.md
          - Mailing: topicos/morar-bem/processos/mailing.md
      - Tabelas:
          - Tabelas: topicos/morar-bem/tabelas/tabelas.md
  - Web Services:
      - Gerador de Relatórios: topicos/web-services/gerador-relatorios.md
      - Observer: topicos/web-services/observer.md

# Plugins
plugins:
  - search

# Extra CSS
extra_css:
  - stylesheets/all.css


