name: Deploy MkDocs to Internal Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Runner que tem acesso à VPN

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: |
          mkdocs build

      - name: Connect to VPN (openfortivpn)
        run: |
          sudo openfortivpn homeoffice.bsb.brbpo.com.br -u ${{ secrets.VPN_USER }} --trusted-cert ${{ secrets.VPN_CERT }}
        env:
          VPN_USER: dev.idea
          VPN_CERT: 8c69288173ff40ba557a0bdef3c3552984d47a00ca3beaef66b987d544f2425d

      - name: Verify VPN Connection
        run: ifconfig | grep ppp || { echo "VPN failed to connect"; exit 1; }

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        env:
          SERVER_IP: 10.10.10.84

      - name: Deploy to Internal Server via SCP
        run: |
          scp -r ./site ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/mkdocs-site

      - name: Disconnect VPN
        run: |
          sudo pkill openfortivpn
